In [10]:
# Reference:


# dict["key"] returns value
# dict["key"] = "value" adds an item to dict
# dict.keys() returns keys
# dict.values() returns values
# dict.items() returns key value pairs
# if "value" in dict: check if key exists

# list[0:2] returns first 3 items in list
# list.append("value") adds value to list



In [ ]:
# iterates through commodity dictionary

# if selected_countries and selected_commodity and selected_years:
#   for n in selection_dict:
#     for cm in commodity_dict["commodity"]:
#       for y in year_dict["year"]:
#         print (n)
#         print(selection_dict[n][0]["code"])
#         print(cm)
#         print(y)

In [23]:
import cmath
import numpy as np
import pandas as pd
import streamlit as st
from requests.auth import HTTPBasicAuth
import requests
# Need dependency file to support these packages
import geopandas as gpd
from datetime import date

## USDA Export Sales Report (ESR) Data
USDA's Export Sales Reporting Program monitors U.S. agricultural export sales on a daily and weekly basis. Export sales reporting provides a constant stream of up-to-date market information for 40 U.S. agricultural commodities sold abroad.

A single statistic reveals the significance of the program: in a typical year, the program monitors more than 40 percent of total U.S. agricultural exports. The program also serves as an early alert on the possible impact foreign sales have on U.S. supplies and prices.

The weekly U.S. Export Sales report is the most currently available source of U.S. export sales data. The data is used to analyze the overall level of export demand, determine where markets exist, and assess the relative position of U.S. commodities in foreign markets.

In [53]:
from requests.auth import HTTPBasicAuth
# gets data from USDA endpoint and converts response to pandas dataframe
def get_usda_data(endpoint_url):
    # USDA API Key
    key = {"API_KEY": "aefd68b9-cfdc-4c9e-a800-b457ff5adade"}
    request = requests.get(url=endpoint_url, headers=key)
    # convert response to pandas dataframe
    return (pd.read_json(request.text))


In [74]:
# Basic endpoints. See below for endpoints that return data
regions_url = "https://apps.fas.usda.gov/OpenData/api/esr/regions"
country_url = "https://apps.fas.usda.gov/OpenData/api/esr/countries"
data_release_url = "https://apps.fas.usda.gov/OpenData/api/esr/datareleasedates"
commodity_url = "https://apps.fas.usda.gov/OpenData/api/esr/commodities"
units_url = "https://apps.fas.usda.gov/OpenData/api/esr/unitsOfMeasure"


In [ ]:
# Regions with Region ID's
get_usda_data(regions_url)

In [60]:
get_usda_data(country_url)

countryCode countryName               countryDescription  regionId  \
0              1    EUROPEAN   EUROPEAN UNION - 27                    1   
1              2     UNKNOWN                          UNKNOWN        99   
2           1010    GREENLD   GREENLAND                              11   
3           1220    CANADA    CANADA                                 11   
4           1610    MIGUEL    ST. PIERRE AND MIQUELON                11   
..           ...         ...                              ...       ...   
205         9350    GUAM      GUAM                                    9   
206         9410    CAN EN I  CANTON AND ENDERBURY ISLANDS            9   
207         9510    AM SAMOA  AMERICAN SAMOA                          9   
208         9610    NMARIANA  NORTHERN MARIANA ISLANDS                9   
209         9800    US O IS   US MINOR OUTLYING ISLAND                9   

    gencCode  
0       None  
1        AX1  
2        GRL  
3        CAN  
4       None  
..       ...  
205      GUM  
206     None  
207      ASM  
208      MNP  
209     None  

[210 rows x 5 columns]

In [ ]:
get_usda_data(commodity_url)

In [ ]:
get_usda_data(data_release_url)

In [63]:
# Units of commodities referenced in chart above.
get_usda_data(units_url)

unitId      unitNames
0       1    Metric Tons
1       2  Running Bales
2       3         Pieces
3       4         NUMBER
4       5         Pounds

Given Commodity Code (Ex: 107 for "All Wheat") and MarketYear (Ex: 2021) this API End point will return a list of US Export records of White Wheat to all applicable countries from USA for the given Market Year. See DataReleaseDates end point to get a list of all Commodities and the corresponding Market Year data.

In [70]:
# return first 5 rows for "All Wheat" in 2021
wheat_url = "https://apps.fas.usda.gov/OpenData/api/esr/exports/commodityCode/107/allCountries/marketYear/2021"
get_usda_data(wheat_url).head(5)

commodityCode  countryCode  weeklyExports  accumulatedExports  \
0            107         1220              0                   0   
1            107         2010          13506               13506   
2            107         2050              0                   0   
3            107         2080              0                   0   
4            107         2110              0                   0   

   outstandingSales  grossNewSales  currentMYNetSales  \
0              9266           9266                  0   
1            352846         224335              25376   
2             95999          95999              95999   
3              4000              0                  0   
4             10000              0                  0   

   currentMYTotalCommitment  nextMYOutstandingSales  nextMYNetSales  unitId  \
0                      9266                       0               0       1   
1                    366352                       0               0       1   
2                     95999                       0               0       1   
3                      4000                       0               0       1   
4                     10000                       0               0       1   

        weekEndingDate  
0  2020-06-04T00:00:00  
1  2020-06-04T00:00:00  
2  2020-06-04T00:00:00  
3  2020-06-04T00:00:00  
4  2020-06-04T00:00:00

Given Commodity Code (Ex: 107 for "All Wheat"), Country Code (Ex:1220 for Canada) and MarketYear (Ex: 2021) this API End point will return a list of US Export records of White Wheat to Canada from USA for the give Market Year. Please see DataReleaseDates end point to get a list of all Commodities and the corresponding Market Year data.

In [73]:
# return first 5 rows for "All Wheat" in 2021
canada_wheat_url = "https://apps.fas.usda.gov/OpenData/api/esr/exports/commodityCode/107/countryCode/2021/marketYear/1220"
get_usda_data(wheat_url).head(5)

commodityCode  countryCode  weeklyExports  accumulatedExports  \
0            107         1220              0                   0   
1            107         2010          13506               13506   
2            107         2050              0                   0   
3            107         2080              0                   0   
4            107         2110              0                   0   

   outstandingSales  grossNewSales  currentMYNetSales  \
0              9266           9266                  0   
1            352846         224335              25376   
2             95999          95999              95999   
3              4000              0                  0   
4             10000              0                  0   

   currentMYTotalCommitment  nextMYOutstandingSales  nextMYNetSales  unitId  \
0                      9266                       0               0       1   
1                    366352                       0               0       1   
2                     95999                       0               0       1   
3                      4000                       0               0       1   
4                     10000                       0               0       1   

        weekEndingDate  
0  2020-06-04T00:00:00  
1  2020-06-04T00:00:00  
2  2020-06-04T00:00:00  
3  2020-06-04T00:00:00  
4  2020-06-04T00:00:00

In [32]:
# Endpoints
regions = "https://apps.fas.usda.gov/OpenData/api/esr/regions"
countries = "https://apps.fas.usda.gov/OpenData/api/esr/countries"
commodities = "https://apps.fas.usda.gov/OpenData/api/esr/commodities"
unitsofmeasure = "https://apps.fas.usda.gov/OpenData/api/esr/commodities"
wheat = "https://apps.fas.usda.gov/OpenData/exports/commodityCode/101/allCountries/marketYear/2021"
endpointlist = [regions, countries, commodities, unitsofmeasure, wheat]
for u in endpointlist:
    headers_dict = {"API_KEY": "aefd68b9-cfdc-4c9e-a800-b457ff5adade"}
    URL = u
    data = requests.get(url=URL, headers=headers_dict)
    # create list of dictionaries.
    u = pd.read_json(data.text)

SyntaxError: 'return' outside function (400053902.py, line 7)

In [28]:
regions

'https://apps.fas.usda.gov/OpenData/api/esr/regions'

In [ ]:
# "https://apps.fas.usda.gov/OpenData/exports/commodityCode/{commodityCode}/allCountries/marketYear/{marketYear}"
# "https://apps.fas.usda.gov/OpenData/exports/commodityCode/{commodityCode}/countryCode/{countryCode}/marketYear/{marketYear}"

In [ ]:
"https://apps.fas.usda.gov/OpenData/exports/commodityCode/101/allCountries/marketYear/2021"

ideas for where this should go next:
- create an interface to visualize per comodity code (emoji?) per country per year
- perhaps multiple visuzalizations with different pivots on the data (e.g. country, year, comodity)
- aggregate dashboard view showing all data
- map view of all this
- 

In [1]:
regions = "https://apps.fas.usda.gov/OpenData/api/esr/regions"
countries = "https://apps.fas.usda.gov/OpenData/api/esr/countries"
commodities = "https://apps.fas.usda.gov/OpenData/api/esr/commodities"
unitsofmeasure = "https://apps.fas.usda.gov/OpenData/api/esr/commodities"
wheat = "https://apps.fas.usda.gov/OpenData/api/esr/exports/commodityCode/101/allCountries/marketYear/2021"
endpointlist = [regions, countries, commodities, unitsofmeasure, wheat]

In [55]:
from lib2to3.pgen2.pgen import DFAState
headers_dict = {"API_KEY": "aefd68b9-cfdc-4c9e-a800-b457ff5adade"}
URL = countries
data = requests.get(url=URL, headers=headers_dict)
# print(data.text)
countrydf = pd.read_json(data.text)
# st.table(pd.read_json(data.text))
# chosencountry = st.multiselect("country", pd.read_json(data.text)["countryDescription"])
# st.write('You selected:', chosencountry)
countrydf

countryCode countryName               countryDescription  regionId  \
0              1    EUROPEAN   EUROPEAN UNION - 27                    1   
1              2     UNKNOWN                          UNKNOWN        99   
2           1010    GREENLD   GREENLAND                              11   
3           1220    CANADA    CANADA                                 11   
4           1610    MIGUEL    ST. PIERRE AND MIQUELON                11   
..           ...         ...                              ...       ...   
205         9350    GUAM      GUAM                                    9   
206         9410    CAN EN I  CANTON AND ENDERBURY ISLANDS            9   
207         9510    AM SAMOA  AMERICAN SAMOA                          9   
208         9610    NMARIANA  NORTHERN MARIANA ISLANDS                9   
209         9800    US O IS   US MINOR OUTLYING ISLAND                9   

    gencCode  
0       None  
1        AX1  
2        GRL  
3        CAN  
4       None  
..       ...  
205      GUM  
206     None  
207      ASM  
208      MNP  
209     None  

[210 rows x 5 columns]

In [57]:
# This string returns the country code based on the country name.
countrydf.loc[(countrydf['countryName'].str.contains('CANADA', case=False)), 'countryCode'].iloc[0]


1220